apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask  # This label must match the selector in the service
spec:
  containers:
  - name: flask-container
    image: siddharthcv77/todo_app-web:latest
    ports:
    - containerPort: 5000
