apiVersion: v1
kind: Service
metadata:
  name: db  # This will be the hostname Flask uses to connect
spec:
  selector:
    app: mongodb  # This label must match the label used in your mongo-pod.yaml
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
